### ISSUE TITLE
XY Plot with Pipe Loader SDXL Not Working in comfy commit fbf68c4e522bada2b847b589088ef248847f2a63

### ISSUE THREAD

**Issue by boricuapab** [TinyTerra/ComfyUI_tinyterraNodes#162]
```
!!! Exception during processing !!! cleanup_models() got an unexpected keyword argument 'keep_clone_weights_loaded'
Traceback (most recent call last):
  File "C:\comfyADMDLoraTrain\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyADMDLoraTrain\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyADMDLoraTrain\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfyADMDLoraTrain\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyADMDLoraTrain\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\tinyterraNodes.py", line 2476, in sample
    return process_xyPlot(model, clip, latent, vae, seed, positive, negative, lora_name, lora_strength, lora_strength, steps, cfg, sampler_name,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyADMDLoraTrain\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\tinyterraNodes.py", line 2448, in process_xyPlot
    plot_image, images, samples = plotter.xy_plot_process()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyADMDLoraTrain\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\tinyterraNodes.py", line 844, in xy_plot_process
    self.execute_prompt(y_prompt, self.extra_pnginfo, x_label, y_label, z_label)
  File "C:\comfyADMDLoraTrain\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\tinyterraNodes.py", line 738, in execute_prompt
    self.executor.execute(prompt, self.num, extra_data, valid[2])
  File "C:\comfyADMDLoraTrain\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\ttNexecutor.py", line 466, in execute
    comfy.model_management.cleanup_models(keep_clone_weights_loaded=True)
TypeError: cleanup_models() got an unexpected keyword argument 'keep_clone_weights_loaded'

Prompt executed in 41.82 seconds
```

**Comment by alenknight** [comment]
i'm having the same issue.

**Comment by Moonlight63** [comment]
Came here to report same

**Comment by alenknight** [comment]
> Came here to report same
> 
> EDIT: To assist with anyone facing this issue, the offending change from comfy is right here: [comfyanonymous/ComfyUI@79d5cea#diff-c43913f04f43d976f3ec095cfcb3981df79c55947e3efbe70799cd374905c773L571](https://github.com/comfyanonymous/ComfyUI/commit/79d5ceae6efe458302899a28496b0daf59890109#diff-c43913f04f43d976f3ec095cfcb3981df79c55947e3efbe70799cd374905c773L571)
> 
> If you want a quick patch, you can manually edit custom_nodes/ComfyUI_tinyterraNodes/ttNpy/ttNexecutor.py line 466 and remove the argument in the (). I am not making a PR for this change because this would probably break backwards compatibility in some way, but IDK.

this worked!  thank you!  for now at least till patched I can use this.
